In [1]:
import hdbscan
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
daejeon = pd.read_csv('_2_HDBSCAN csv파일//daejeon.csv', encoding = 'utf-8', index_col = 0)
sejong = pd.read_csv('_2_HDBSCAN csv파일//sejong.csv', encoding = 'utf-8', index_col = 0)
chungnam = pd.read_csv('_2_HDBSCAN csv파일//chungnam.csv', encoding = 'utf-8', index_col = 0)
display(daejeon)
display(sejong)
display(chungnam)

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                             
2020-12-01 07:08:44     대전광역시 중구 석교동(석교동) 85-14  127.447545  36.306724   
2020-12-01 07:09:20  대전광역시 중구 석교동(행정:석교동) 88-11  127.447175  36.306694   
2020-12-01 01:39:03   대전광역시 동구 대동(행정:대동) 355-14  127.447390  36.324597   
2020-12-01 00:12:30    대전광역시 유성구 교촌동(진잠동) 411-1  127.308197  36.308033   
2020-12-01 00:09:52    대전광역시 유성구 교촌동(진잠동) 411-1  127.308197  36.308033   
...                                         ...         ...        ...   
2020-11-20 09:01:14                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 11:09:05                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 14:47:06                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 17:59:14                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 09:55:10                대전광역시 중구 중촌동  127.404663  36.341685   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 07:08:44         20          12         1          7  
2020-12-01 07:09:20         20          12         1          7  
2020-12-01 01:39:03         20          12         1          1  
2020-12-01 00:12:30         20          12         1          0  
2020-12-01 00:09:52         20          12         1          0  
...                        ...         ...       ...        ...  
2020-11-20 09:01:14         20          11        20          9  
2020-11-20 11:09:05         20          11        20         11  
2020-11-20 14:47:06         20          11        20         14  
2020-11-20 17:59:14         20          11        20         17  
2020-11-20 09:55:10         20          11        20          9  

[104780 rows x 7 columns]

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                                 
2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180  36.601510   
2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611  36.603134   
2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902  36.522225   
2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694  36.717396   
2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969  36.504865   
...                                             ...         ...        ...   
2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495  36.503282   
2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927  36.491494   
2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602  36.514305   
2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436  36.572830   
2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246  36.526412   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 13:22:45         20          12         1         13  
2020-12-01 10:45:45         20          12         1         10  
2020-12-01 13:07:38         20          12         1         13  
2020-12-01 12:21:09         20          12         1         12  
2020-12-01 16:51:57         20          12         1         16  
...                        ...         ...       ...        ...  
2020-11-20 10:12:32         20          11        20         10  
2020-02-24 13:18:01         20           2        24         13  
2020-04-03 21:09:28         20           4         3         21  
2020-09-15 16:24:11         20           9        15         16  
2020-10-23 09:00:51         20          10        23          9  

[13420 rows x 7 columns]

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                                 
2020-12-01 08:17:50  충청남도 천안시 서북구 성정동(행정:성정2동) 1259  127.137160  36.826718   
2020-12-01 01:36:38  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290  36.967612   
2020-12-01 02:23:03  충청남도 아산시 둔포면 송용리(행정:둔포면) 71-68  127.032318  36.921510   
2020-12-01 02:24:26         충청남도 서산시 읍내동(부춘동) 733-2  126.438445  36.779188   
2020-12-01 01:37:37     충청남도 서산시 대산읍 대로리(대산읍) 216-3  126.412245  36.967579   
...                                             ...         ...        ...   
2020-08-18 13:58:20                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-08-23 19:19:32                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-09-01 10:18:15                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-10-04 00:00:12                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-10-24 18:50:12                충청남도 태안군 근흥면 도황리  126.191890  36.690215   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 08:17:50         20          12         1          8  
2020-12-01 01:36:38         20          12         1          1  
2020-12-01 02:23:03         20          12         1          2  
2020-12-01 02:24:26         20          12         1          2  
2020-12-01 01:37:37         20          12         1          1  
...                        ...         ...       ...        ...  
2020-08-18 13:58:20         20           8        18         13  
2020-08-23 19:19:32         20           8        23         19  
2020-09-01 10:18:15         20           9         1         10  
2020-10-04 00:00:12         20          10         4          0  
2020-10-24 18:50:12         20          10        24         18  

[137858 rows x 7 columns]

### 대전 

In [3]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_dae = hdbscan.HDBSCAN(min_cluster_size =50, min_samples = 50, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_dae.fit(
    np.radians(
        [x for x in zip(daejeon['HPPN_Y'],daejeon['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=50, min_samples=50)

In [4]:
np.unique(clusterer_dae.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [5]:
daejeon['cluster'] = clusterer_dae.labels_

In [6]:
daejeon = daejeon[daejeon['cluster']!='75'].reset_index()

In [8]:
daejeon.to_csv('_2_HDBSCAN csv파일//daejeon_eom_50.csv')

### 충남 

In [9]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_chg = hdbscan.HDBSCAN(min_cluster_size =40, min_samples = 40, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_chg.fit(
    np.radians(
        [x for x in zip(chungnam['HPPN_Y'],chungnam['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=40, min_samples=40)

In [10]:
np.unique(clusterer_chg.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [11]:
chungnam['cluster'] = clusterer_chg.labels_

In [12]:
chungnam.to_csv('_2_HDBSCAN csv파일//chungnam_eom_40.csv')

### 세종 

In [13]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_sej = hdbscan.HDBSCAN(min_cluster_size =50, min_samples = 50, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_sej.fit(
    np.radians(
        [x for x in zip(sejong['HPPN_Y'],sejong['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=50, min_samples=50)

In [14]:
np.unique(clusterer_sej.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64),
 array([7011,  131,  142,   69,   61,  317,   70,  147,   82,   80,   91,
          72,   75,   61,  305,   54,   71,  180,   86,  255,   70,  127,
          83,  149,  315,   82,  291,  232,  129,   57,  101,  128,  252,
          89,  211,  136,  307,   65,  103,  233,   51,  117,   50,   67,
         438,  118,   59], dtype=int64))

In [15]:
sejong['cluster'] = clusterer_sej.labels_

In [16]:
sejong.to_csv('_2_HDBSCAN csv파일//sejong_eom_50.csv')

### 노이즈 제외 추출 

In [17]:
d_50 = pd.read_csv('_2_HDBSCAN csv파일//daejeon_eom_50.csv')
c_40 = pd.read_csv('_2_HDBSCAN csv파일//chungnam_eom_40.csv')
s_50 = pd.read_csv('_2_HDBSCAN csv파일//sejong_eom_50.csv')
display(d_50)
display(c_40)
display(s_50)

Unnamed: 0         RECV_CPLT_DM               HPPN_PNU_ADDR  \
0                0  2020-12-01 07:08:44     대전광역시 중구 석교동(석교동) 85-14   
1                1  2020-12-01 07:09:20  대전광역시 중구 석교동(행정:석교동) 88-11   
2                2  2020-12-01 01:39:03   대전광역시 동구 대동(행정:대동) 355-14   
3                3  2020-12-01 00:12:30    대전광역시 유성구 교촌동(진잠동) 411-1   
4                4  2020-12-01 00:09:52    대전광역시 유성구 교촌동(진잠동) 411-1   
...            ...                  ...                         ...   
104775      104775  2020-11-20 09:01:14                대전광역시 중구 중촌동   
104776      104776  2020-11-20 11:09:05                대전광역시 중구 중촌동   
104777      104777  2020-11-20 14:47:06                대전광역시 중구 중촌동   
104778      104778  2020-11-20 17:59:14                대전광역시 중구 중촌동   
104779      104779  2020-11-20 09:55:10                대전광역시 중구 중촌동   

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
2       127.447390  36.324597         20          12         1          1   
3       127.308197  36.308033         20          12         1          0   
4       127.308197  36.308033         20          12         1          0   
...            ...        ...        ...         ...       ...        ...   
104775  127.404663  36.341685         20          11        20          9   
104776  127.404663  36.341685         20          11        20         11   
104777  127.404663  36.341685         20          11        20         14   
104778  127.404663  36.341685         20          11        20         17   
104779  127.404663  36.341685         20          11        20          9   

        cluster  
0            87  
1            87  
2            -1  
3            -1  
4            -1  
...         ...  
104775       75  
104776       75  
104777       75  
104778       75  
104779       75  

[104780 rows x 10 columns]

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0       2020-12-01 08:17:50  충청남도 천안시 서북구 성정동(행정:성정2동) 1259  127.137160   
1       2020-12-01 01:36:38  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290   
2       2020-12-01 02:23:03  충청남도 아산시 둔포면 송용리(행정:둔포면) 71-68  127.032318   
3       2020-12-01 02:24:26         충청남도 서산시 읍내동(부춘동) 733-2  126.438445   
4       2020-12-01 01:37:37     충청남도 서산시 대산읍 대로리(대산읍) 216-3  126.412245   
...                     ...                             ...         ...   
137853  2020-08-18 13:58:20                충청남도 태안군 근흥면 도황리  126.191890   
137854  2020-08-23 19:19:32                충청남도 태안군 근흥면 도황리  126.191890   
137855  2020-09-01 10:18:15                충청남도 태안군 근흥면 도황리  126.191890   
137856  2020-10-04 00:00:12                충청남도 태안군 근흥면 도황리  126.191890   
137857  2020-10-24 18:50:12                충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
0       36.826718         20          12         1          8      542  
1       36.967612         20          12         1          1      140  
2       36.921510         20          12         1          2       -1  
3       36.779188         20          12         1          2       -1  
4       36.967579         20          12         1          1      140  
...           ...        ...         ...       ...        ...      ...  
137853  36.690215         20           8        18         13      118  
137854  36.690215         20           8        23         19      118  
137855  36.690215         20           9         1         10      118  
137856  36.690215         20          10         4          0      118  
137857  36.690215         20          10        24         18      118  

[137858 rows x 9 columns]

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0      2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180   
1      2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611   
2      2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902   
3      2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694   
4      2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969   
...                    ...                             ...         ...   
13415  2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495   
13416  2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927   
13417  2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602   
13418  2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436   
13419  2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246   

          HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
0      36.601510         20          12         1         13       -1  
1      36.603134         20          12         1         10       21  
2      36.522225         20          12         1         13        4  
3      36.717396         20          12         1         12       -1  
4      36.504865         20          12         1         16       -1  
...          ...        ...         ...       ...        ...      ...  
13415  36.503282         20          11        20         10       -1  
13416  36.491494         20           2        24         13       -1  
13417  36.514305         20           4         3         21       35  
13418  36.572830         20           9        15         16       -1  
13419  36.526412         20          10        23          9       -1  

[13420 rows x 9 columns]

In [18]:
print(np.unique(d_50['cluster'],return_counts = True))
print(np.unique(c_40['cluster'],return_counts = True))
print(np.unique(s_50['cluster'],return_counts = True))

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [19]:
d_wn = d_50[d_50['cluster'] != -1]
c_wn = c_40[c_40['cluster'] != -1]
s_wn = s_50[s_50['cluster'] != -1]

display(d_wn)
display(c_wn)
display(s_wn)

Unnamed: 0         RECV_CPLT_DM               HPPN_PNU_ADDR  \
0                0  2020-12-01 07:08:44     대전광역시 중구 석교동(석교동) 85-14   
1                1  2020-12-01 07:09:20  대전광역시 중구 석교동(행정:석교동) 88-11   
5                5  2020-12-01 00:22:16  대전광역시 서구 괴정동(행정:괴정동) 95-28   
7                7  2020-12-01 15:05:21        대전광역시 중구 문화동(문화1동) 6   
8                8  2020-12-01 15:03:46  대전광역시 유성구 복용동(행정:온천1동) 236   
...            ...                  ...                         ...   
104775      104775  2020-11-20 09:01:14                대전광역시 중구 중촌동   
104776      104776  2020-11-20 11:09:05                대전광역시 중구 중촌동   
104777      104777  2020-11-20 14:47:06                대전광역시 중구 중촌동   
104778      104778  2020-11-20 17:59:14                대전광역시 중구 중촌동   
104779      104779  2020-11-20 09:55:10                대전광역시 중구 중촌동   

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
5       127.382337  36.336437         20          12         1          0   
7       127.413504  36.317088         20          12         1         15   
8       127.320380  36.338273         20          12         1         15   
...            ...        ...        ...         ...       ...        ...   
104775  127.404663  36.341685         20          11        20          9   
104776  127.404663  36.341685         20          11        20         11   
104777  127.404663  36.341685         20          11        20         14   
104778  127.404663  36.341685         20          11        20         17   
104779  127.404663  36.341685         20          11        20          9   

        cluster  
0            87  
1            87  
5           250  
7           147  
8            12  
...         ...  
104775       75  
104776       75  
104777       75  
104778       75  
104779       75  

[52534 rows x 10 columns]

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0       2020-12-01 08:17:50  충청남도 천안시 서북구 성정동(행정:성정2동) 1259  127.137160   
1       2020-12-01 01:36:38  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290   
4       2020-12-01 01:37:37     충청남도 서산시 대산읍 대로리(대산읍) 216-3  126.412245   
5       2020-12-01 01:38:31  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290   
8       2020-12-01 01:06:14   충청남도 천안시 서북구 두정동(행정:부성2동) 886  127.135456   
...                     ...                             ...         ...   
137853  2020-08-18 13:58:20                충청남도 태안군 근흥면 도황리  126.191890   
137854  2020-08-23 19:19:32                충청남도 태안군 근흥면 도황리  126.191890   
137855  2020-09-01 10:18:15                충청남도 태안군 근흥면 도황리  126.191890   
137856  2020-10-04 00:00:12                충청남도 태안군 근흥면 도황리  126.191890   
137857  2020-10-24 18:50:12                충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
0       36.826718         20          12         1          8      542  
1       36.967612         20          12         1          1      140  
4       36.967579         20          12         1          1      140  
5       36.967612         20          12         1          1      140  
8       36.832394         20          12         1          1      558  
...           ...        ...         ...       ...        ...      ...  
137853  36.690215         20           8        18         13      118  
137854  36.690215         20           8        23         19      118  
137855  36.690215         20           9         1         10      118  
137856  36.690215         20          10         4          0      118  
137857  36.690215         20          10        24         18      118  

[75726 rows x 9 columns]

RECV_CPLT_DM                      HPPN_PNU_ADDR      HPPN_X  \
1      2020-12-01 10:45:45     세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611   
2      2020-12-01 13:07:38       세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902   
7      2020-12-01 21:00:31      세종특별자치시 세종시 보람동(행정:보람동) 622-1  127.293270   
10     2020-12-04 01:17:57           세종특별자치시 세종시 나성동(새롬동) 721  127.262514   
11     2020-12-04 01:16:44        세종특별자치시 세종시 나성동(행정:새롬동) 722  127.262247   
...                    ...                                ...         ...   
13405  2020-11-21 21:03:16  세종특별자치시 세종시 조치원읍 교리(행정:조치원읍) 10-4  127.298023   
13410  2020-11-20 11:53:56        세종특별자치시 세종시 한솔동(한솔동) 130-2   127.253278   
13411  2020-11-20 13:28:14        세종특별자치시 세종시 보람동(행정:보람동) 670  127.291009   
13412  2020-11-20 10:53:56    세종특별자치시 세종시 부강면 부강리(행정:부강면) 481  127.368017   
13417  2020-04-03 21:09:28                        세종특별자치시 도담동  127.258602   

          HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
1      36.603134         20          12         1         10       21  
2      36.522225         20          12         1         13        4  
7      36.482200         20          12         1         21       23  
10     36.480017         20          12         4          1       44  
11     36.479612         20          12         4          1       44  
...          ...        ...         ...       ...        ...      ...  
13405  36.604357         20          11        21         21       24  
13410  36.473544         20          11        20         11       13  
13411  36.477561         20          11        20         13       23  
13412  36.528288         20          11        20         10        4  
13417  36.514305         20           4         3         21       35  

[6409 rows x 9 columns]

In [20]:
from datetime import datetime
d_wn['RECV_CPLT_DM'] = pd.to_datetime(d_wn['RECV_CPLT_DM'])
c_wn['RECV_CPLT_DM'] = pd.to_datetime(c_wn['RECV_CPLT_DM'])
s_wn['RECV_CPLT_DM'] = pd.to_datetime(s_wn['RECV_CPLT_DM'])

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_22980\1088886608.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_wn['RECV_CPLT_DM'] = pd.to_datetime(d_wn['RECV_CPLT_DM'])
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_22980\1088886608.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_wn['RECV_CPLT_DM'] = pd.to_datetime(c_wn['RECV_CPLT_DM'])
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_22980\1088886608.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
T

In [21]:
d_wn.to_csv('_2_HDBSCAN csv파일//daejeon_no noise.csv',mode="w",encoding='utf-8',index=False)
c_wn.to_csv('_2_HDBSCAN csv파일//chungnam_no noise.csv',mode="w",encoding='utf-8',index=False)
s_wn.to_csv('_2_HDBSCAN csv파일//sejong_no noise.csv',mode="w",encoding='utf-8',index=False)