In [1]:
import hdbscan
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
daejeon = pd.read_csv('_4_HDBSCAN_요인별추출//daejeon.csv', encoding = 'utf-8', index_col = 0)
sejong = pd.read_csv('_4_HDBSCAN_요인별추출//sejong.csv', encoding = 'utf-8', index_col = 0)
chungnam = pd.read_csv('_4_HDBSCAN_요인별추출//chungnam.csv', encoding = 'utf-8', index_col = 0)
display(daejeon)
display(sejong)
display(chungnam)

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                             
2020-12-01 07:08:44     대전광역시 중구 석교동(석교동) 85-14  127.447545  36.306724   
2020-12-01 07:09:20  대전광역시 중구 석교동(행정:석교동) 88-11  127.447175  36.306694   
2020-12-01 01:39:03   대전광역시 동구 대동(행정:대동) 355-14  127.447390  36.324597   
2020-12-01 00:12:30    대전광역시 유성구 교촌동(진잠동) 411-1  127.308197  36.308033   
2020-12-01 00:09:52    대전광역시 유성구 교촌동(진잠동) 411-1  127.308197  36.308033   
...                                         ...         ...        ...   
2020-11-20 09:01:14                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 11:09:05                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 14:47:06                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 17:59:14                대전광역시 중구 중촌동  127.404663  36.341685   
2020-11-20 09:55:10                대전광역시 중구 중촌동  127.404663  36.341685   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 07:08:44         20          12         1          7  
2020-12-01 07:09:20         20          12         1          7  
2020-12-01 01:39:03         20          12         1          1  
2020-12-01 00:12:30         20          12         1          0  
2020-12-01 00:09:52         20          12         1          0  
...                        ...         ...       ...        ...  
2020-11-20 09:01:14         20          11        20          9  
2020-11-20 11:09:05         20          11        20         11  
2020-11-20 14:47:06         20          11        20         14  
2020-11-20 17:59:14         20          11        20         17  
2020-11-20 09:55:10         20          11        20          9  

[104780 rows x 7 columns]

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                                 
2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180  36.601510   
2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611  36.603134   
2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902  36.522225   
2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694  36.717396   
2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969  36.504865   
...                                             ...         ...        ...   
2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495  36.503282   
2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927  36.491494   
2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602  36.514305   
2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436  36.572830   
2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246  36.526412   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 13:22:45         20          12         1         13  
2020-12-01 10:45:45         20          12         1         10  
2020-12-01 13:07:38         20          12         1         13  
2020-12-01 12:21:09         20          12         1         12  
2020-12-01 16:51:57         20          12         1         16  
...                        ...         ...       ...        ...  
2020-11-20 10:12:32         20          11        20         10  
2020-02-24 13:18:01         20           2        24         13  
2020-04-03 21:09:28         20           4         3         21  
2020-09-15 16:24:11         20           9        15         16  
2020-10-23 09:00:51         20          10        23          9  

[13420 rows x 7 columns]

HPPN_PNU_ADDR      HPPN_X     HPPN_Y  \
RECV_CPLT_DM                                                                 
2020-12-01 08:17:50  충청남도 천안시 서북구 성정동(행정:성정2동) 1259  127.137160  36.826718   
2020-12-01 01:36:38  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290  36.967612   
2020-12-01 02:23:03  충청남도 아산시 둔포면 송용리(행정:둔포면) 71-68  127.032318  36.921510   
2020-12-01 02:24:26         충청남도 서산시 읍내동(부춘동) 733-2  126.438445  36.779188   
2020-12-01 01:37:37     충청남도 서산시 대산읍 대로리(대산읍) 216-3  126.412245  36.967579   
...                                             ...         ...        ...   
2020-08-18 13:58:20                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-08-23 19:19:32                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-09-01 10:18:15                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-10-04 00:00:12                충청남도 태안군 근흥면 도황리  126.191890  36.690215   
2020-10-24 18:50:12                충청남도 태안군 근흥면 도황리  126.191890  36.690215   

                     RECV_year  RECV_month  RECV_day  RECV_hour  
RECV_CPLT_DM                                                     
2020-12-01 08:17:50         20          12         1          8  
2020-12-01 01:36:38         20          12         1          1  
2020-12-01 02:23:03         20          12         1          2  
2020-12-01 02:24:26         20          12         1          2  
2020-12-01 01:37:37         20          12         1          1  
...                        ...         ...       ...        ...  
2020-08-18 13:58:20         20           8        18         13  
2020-08-23 19:19:32         20           8        23         19  
2020-09-01 10:18:15         20           9         1         10  
2020-10-04 00:00:12         20          10         4          0  
2020-10-24 18:50:12         20          10        24         18  

[137858 rows x 7 columns]

## 대전 

In [4]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_dae = hdbscan.HDBSCAN(min_cluster_size =50, min_samples = 50, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_dae.fit(
    np.radians(
        [x for x in zip(daejeon['HPPN_Y'],daejeon['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=50, min_samples=50)

In [5]:
np.unique(clusterer_dae.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [6]:
daejeon['cluster'] = clusterer_dae.labels_

In [23]:
daejeon.to_csv('_4_HDBSCAN_요인별추출//daejeon_eom_50.csv')

### 대전 - 연도별

In [6]:
daejeon_20 = daejeon[daejeon['RECV_year'] == 20]
daejeon_21 = daejeon[daejeon['RECV_year'] == 21]
daejeon_22 = daejeon[daejeon['RECV_year'] == 22]
print(daejeon_20.shape)
print(daejeon_21.shape)
print(daejeon_22.shape)

(36688, 12)
(33208, 12)
(33298, 12)


In [72]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_dae_22 = hdbscan.HDBSCAN(min_cluster_size =20, min_samples = 20, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_dae_22.fit(
    np.radians(
        [x for x in zip(daejeon_22['HPPN_Y'],daejeon_22['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=20, min_samples=20)

In [73]:
daejeon_22['cluster'] = clusterer_dae_22.labels_

<ipython-input-73-6f60ea69e59f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daejeon_22['cluster'] = clusterer_dae_22.labels_


In [74]:
np.unique(clusterer_dae_22.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [75]:
daejeon_22.to_csv('_4_HDBSCAN_요인별추출//daejeon_2022_minpt_20.csv')

### 대전 - 계절별 

In [81]:
daejeon_spring = daejeon[np.logical_and(daejeon['RECV_month'] >=3 ,daejeon['RECV_month'] <= 5 ) ]
daejeon_summer = daejeon[np.logical_and(daejeon['RECV_month'] >=6 ,daejeon['RECV_month'] <= 8 ) ]
daejeon_fall = daejeon[np.logical_and(daejeon['RECV_month'] >=9 ,daejeon['RECV_month'] <= 11 ) ]
daejeon_winter = daejeon[np.logical_or(daejeon['RECV_month'] ==12 ,daejeon['RECV_month'] <= 2 ) ]

print(daejeon_spring.shape)
print(daejeon_summer.shape)
print(daejeon_fall.shape)
print(daejeon_winter.shape)

(24650, 12)
(27462, 12)
(27684, 12)
(24984, 12)


In [122]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_winter = hdbscan.HDBSCAN(min_cluster_size =20, min_samples = 20, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_winter.fit(
    np.radians(
        [x for x in zip(daejeon_winter['HPPN_Y'],daejeon_winter['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=20, min_samples=20)

In [123]:
daejeon_winter['cluster'] = clusterer_winter.labels_

<ipython-input-123-d2263953a70b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daejeon_winter['cluster'] = clusterer_winter.labels_


In [124]:
np.unique(clusterer_winter.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [125]:
daejeon_winter.to_csv('_4_HDBSCAN_요인별추출//daejeon_winter_minpt_20.csv')

### 대전 - 요일별 

In [132]:
daejeon = daejeon.reset_index()
daejeon['RECV_CPLT_DM'] = pd.to_datetime(daejeon['RECV_CPLT_DM'])
display(daejeon)

RECV_CPLT_DM  EVT_CL_CD                         HPPN_PNU_ADDR  \
0      2001-12-20 07:08:44        401               대전광역시 중구 석교동(석교동) 85-14   
1      2001-12-20 07:09:20        401            대전광역시 중구 석교동(행정:석교동) 88-11   
2      2001-12-20 01:39:03        401             대전광역시 동구 대동(행정:대동) 355-14   
3      2001-12-20 00:12:30        401              대전광역시 유성구 교촌동(진잠동) 411-1   
4      2001-12-20 00:09:52        401              대전광역시 유성구 교촌동(진잠동) 411-1   
...                    ...        ...                                   ...   
104775 2023-08-20 17:24:25        401               대전 중구 부사동 255-1  255-1    
104776 2011-09-20 19:08:40        401                 대전 서구 도안동 1502  1502    
104777 2019-09-20 21:03:55        401               대전 서구 복수동 257-3  257-3    
104778 2004-10-20 13:43:05        401                대전 서구 갈마1동 1268  1268    
104779 2013-11-20 18:42:05        401  대전 서구 둔산1동 915 청사오피스텔,  915 청사오피스텔,    

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
2       127.447390  36.324597         20          12         1          1   
3       127.308197  36.308033         20          12         1          0   
4       127.308197  36.308033         20          12         1          0   
...            ...        ...        ...         ...       ...        ...   
104775  127.436670  36.312140         20           8        23         17   
104776  127.347620  36.320900         20           9        11         19   
104777  127.375010  36.304440         20           9        19         21   
104778  127.373930  36.346500         20          10         4         13   
104779  127.389100  36.359430         20          11        13         18   

        RECV_minute  RECV_second  \
0                 8           44   
1                 9           20   
2                39            3   
3                12           30   
4                 9           52   
...             ...          ...   
104775           24           25   
104776            8           40   
104777            3           55   
104778           43            5   
104779           42            5   

                                       total_address   city  
0             대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시  
1             대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시  
2                    대동초등1길, 대동, 동구, 대전, 34659, 대한민국  대전광역시  
3           호남고속도로지선, 교촌동, 진잠동, 유성구, 대전, 34228, 대한민국  대전광역시  
4           호남고속도로지선, 교촌동, 진잠동, 유성구, 대전, 34228, 대한민국  대전광역시  
...                                              ...    ...  
104775                대정동, 진잠동, 유성구, 대전, 34212, 대한민국     대전  
104776        102, 탕정면로, 명암리, 아산시, 충청남도, 31456, 대한민국     대전  
104777  동의한의원, 시민로295번길, 강산동, 논산시, 충청남도, 32981, 대한민국     대전  
104778       고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전  
104779       고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전  

[104780 rows x 13 columns]

In [133]:
daejeon['weekday'] = daejeon['RECV_CPLT_DM'].apply(lambda x: x.weekday())
display(daejeon)

RECV_CPLT_DM  EVT_CL_CD                         HPPN_PNU_ADDR  \
0      2001-12-20 07:08:44        401               대전광역시 중구 석교동(석교동) 85-14   
1      2001-12-20 07:09:20        401            대전광역시 중구 석교동(행정:석교동) 88-11   
2      2001-12-20 01:39:03        401             대전광역시 동구 대동(행정:대동) 355-14   
3      2001-12-20 00:12:30        401              대전광역시 유성구 교촌동(진잠동) 411-1   
4      2001-12-20 00:09:52        401              대전광역시 유성구 교촌동(진잠동) 411-1   
...                    ...        ...                                   ...   
104775 2023-08-20 17:24:25        401               대전 중구 부사동 255-1  255-1    
104776 2011-09-20 19:08:40        401                 대전 서구 도안동 1502  1502    
104777 2019-09-20 21:03:55        401               대전 서구 복수동 257-3  257-3    
104778 2004-10-20 13:43:05        401                대전 서구 갈마1동 1268  1268    
104779 2013-11-20 18:42:05        401  대전 서구 둔산1동 915 청사오피스텔,  915 청사오피스텔,    

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
2       127.447390  36.324597         20          12         1          1   
3       127.308197  36.308033         20          12         1          0   
4       127.308197  36.308033         20          12         1          0   
...            ...        ...        ...         ...       ...        ...   
104775  127.436670  36.312140         20           8        23         17   
104776  127.347620  36.320900         20           9        11         19   
104777  127.375010  36.304440         20           9        19         21   
104778  127.373930  36.346500         20          10         4         13   
104779  127.389100  36.359430         20          11        13         18   

        RECV_minute  RECV_second  \
0                 8           44   
1                 9           20   
2                39            3   
3                12           30   
4                 9           52   
...             ...          ...   
104775           24           25   
104776            8           40   
104777            3           55   
104778           43            5   
104779           42            5   

                                       total_address   city  weekday  
0             대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시        3  
1             대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시        3  
2                    대동초등1길, 대동, 동구, 대전, 34659, 대한민국  대전광역시        3  
3           호남고속도로지선, 교촌동, 진잠동, 유성구, 대전, 34228, 대한민국  대전광역시        3  
4           호남고속도로지선, 교촌동, 진잠동, 유성구, 대전, 34228, 대한민국  대전광역시        3  
...                                              ...    ...      ...  
104775                대정동, 진잠동, 유성구, 대전, 34212, 대한민국     대전        6  
104776        102, 탕정면로, 명암리, 아산시, 충청남도, 31456, 대한민국     대전        1  
104777  동의한의원, 시민로295번길, 강산동, 논산시, 충청남도, 32981, 대한민국     대전        4  
104778       고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전        2  
104779       고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전        2  

[104780 rows x 14 columns]

In [135]:
daejeon_mon = daejeon[daejeon['weekday'] == 0]
daejeon_tue = daejeon[daejeon['weekday'] == 1]
daejeon_wed = daejeon[daejeon['weekday'] == 2]
daejeon_thu = daejeon[daejeon['weekday'] == 3]
daejeon_fri = daejeon[daejeon['weekday'] == 4]
daejeon_sat = daejeon[daejeon['weekday'] == 5]
daejeon_sun = daejeon[daejeon['weekday'] == 6]

print(daejeon_mon.shape)
print(daejeon_tue.shape)
print(daejeon_wed.shape)
print(daejeon_thu.shape)
print(daejeon_fri.shape)
print(daejeon_sat.shape)
print(daejeon_sun.shape)

(14823, 14)
(14826, 14)
(14938, 14)
(14918, 14)
(14919, 14)
(15289, 14)
(15067, 14)


In [217]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_sun = hdbscan.HDBSCAN(min_cluster_size = 30, min_samples = 30, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_sun.fit(
    np.radians(
        [x for x in zip(daejeon_sun['HPPN_Y'],daejeon_sun['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=30, min_samples=30)

In [218]:
daejeon_sun['cluster'] = clusterer_sun.labels_

<ipython-input-218-745ade2b6d18>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daejeon_sun['cluster'] = clusterer_sun.labels_


In [219]:
np.unique(clusterer_sun.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61], dtype=int64),
 array([7671,  385,   75,   31,  219,   47,   32,  171,   93,   48,   81,
         184,  176,   88,   35,  148,  138,   49,   42,   96,   60,   62,
          71,   49,   47,   44,   35,   94,   85,  238,   43,   66,   49,
          49,   39,   30,   59,   65,   78,   74,   63,   79,  482,   57,
          40,   66,  165,   53,   55,   32,  535,   63,   96,   92,  923,
          47,  257,  311,   59,  127,   45,   55,  219], dtype=int64))

In [220]:
daejeon_sun.to_csv('_4_HDBSCAN_요인별추출//daejeon_sun_minpt_30.csv')

### 대전 - 밤낮 

In [56]:
daejeon_day = daejeon[np.logical_and(daejeon['RECV_hour'] > 6, daejeon['RECV_hour'] <= 18)]
daejeon_night = daejeon[np.logical_or(daejeon['RECV_hour'] <= 6, daejeon['RECV_hour'] > 18)]

In [78]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_night = hdbscan.HDBSCAN(min_cluster_size = 30, min_samples = 30, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_night.fit(
    np.radians(
        [x for x in zip(daejeon_night['HPPN_Y'],daejeon_night['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=30, min_samples=30)

In [79]:
daejeon_night['cluster'] = clusterer_night.labels_

<ipython-input-79-377e63a9db82>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  daejeon_night['cluster'] = clusterer_night.labels_


In [80]:
np.unique(clusterer_night.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175], dt

In [81]:
daejeon_night.to_csv('_4_HDBSCAN_요인별추출//daejeon_night_minpt_30.csv')

### 충남 

In [8]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_chg = hdbscan.HDBSCAN(min_cluster_size =40, min_samples = 40, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_chg.fit(
    np.radians(
        [x for x in zip(chungnam['HPPN_Y'],chungnam['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=40, min_samples=40)

In [9]:
np.unique(clusterer_chg.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [10]:
chungnam['cluster'] = clusterer_chg.labels_

In [38]:
chungnam.to_csv('_4_HDBSCAN_요인별추출//chungnam_eom_30.csv')

### 충남 - 연도별 

In [83]:
chungnam_20 = chungnam[chungnam['RECV_year'] == 20]
chungnam_21 = chungnam[chungnam['RECV_year'] == 21]
chungnam_22 = chungnam[chungnam['RECV_year'] == 22]
print(chungnam_20.shape)
print(chungnam_21.shape)
print(chungnam_22.shape)

(53142, 12)
(39202, 12)
(43575, 12)


In [116]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_22 = hdbscan.HDBSCAN(min_cluster_size =30, min_samples = 30, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_22.fit(
    np.radians(
        [x for x in zip(chungnam_22['HPPN_Y'],chungnam_22['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=30, min_samples=30)

In [117]:
chungnam_22['cluster'] = clusterer_22.labels_

<ipython-input-117-2d33eb2b903d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chungnam_22['cluster'] = clusterer_22.labels_


In [118]:
np.unique(clusterer_22.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [119]:
chungnam_22.to_csv('_4_HDBSCAN_요인별추출//chungnam_22_minpt_30.csv')

### 충남 - 계절별 

In [6]:
chungnam_spring = chungnam[np.logical_and(chungnam['RECV_month'] >=3 ,chungnam['RECV_month'] <= 5 ) ]
chungnam_summer = chungnam[np.logical_and(chungnam['RECV_month'] >=6 ,chungnam['RECV_month'] <= 8 ) ]
chungnam_fall = chungnam[np.logical_and(chungnam['RECV_month'] >=9 ,chungnam['RECV_month'] <= 11 ) ]
chungnam_winter = chungnam[np.logical_or(chungnam['RECV_month'] ==12 ,chungnam['RECV_month'] <= 2 ) ]

print(chungnam_spring.shape)
print(chungnam_summer.shape)
print(chungnam_fall.shape)
print(chungnam_winter.shape)

(32116, 12)
(36433, 12)
(37608, 12)
(31701, 12)


In [52]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_winter = hdbscan.HDBSCAN(min_cluster_size = 20, min_samples = 20, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_winter.fit(
    np.radians(
        [x for x in zip(chungnam_winter['HPPN_Y'],chungnam_winter['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=20, min_samples=20)

In [53]:
chungnam_winter['cluster'] = clusterer_winter.labels_

<ipython-input-53-0fa9d2ef975c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chungnam_winter['cluster'] = clusterer_winter.labels_


In [54]:
np.unique(clusterer_winter.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176

In [55]:
chungnam_winter.to_csv('_4_HDBSCAN_요인별추출//chungnam_winter_minpt_20.csv')

### 충남 - 요일별 

In [120]:
chungnam = chungnam.reset_index()
chungnam['RECV_CPLT_DM'] = pd.to_datetime(chungnam['RECV_CPLT_DM'])
display(chungnam)

RECV_CPLT_DM  EVT_CL_CD         HPPN_PNU_ADDR      HPPN_X  \
0      2006-09-21 16:36:37        401           충남 논산시 가야곡면  127.174864   
1      2029-12-21 08:21:39        401  충남 천안시 동남구 신부동 16-11  127.169554   
2      2006-02-22 11:07:22        401    충남 보령시 남포면 옥서리 2-3  126.606069   
3      2027-12-21 16:13:29        401    충남 천안시 서북구 백석동 873  127.125026   
4      2023-12-21 22:01:06        401    충남 천안시 서북구 두정동 939  127.135951   
...                    ...        ...                   ...         ...   
137853 2018-08-20 13:58:20        401      충청남도 태안군 근흥면 도황리  126.191890   
137854 2023-08-20 19:19:32        401      충청남도 태안군 근흥면 도황리  126.191890   
137855 2001-09-20 10:18:15        401      충청남도 태안군 근흥면 도황리  126.191890   
137856 2004-10-20 00:00:12        401      충청남도 태안군 근흥면 도황리  126.191890   
137857 2024-10-20 18:50:12        401      충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  RECV_minute  \
0       36.158793         21           9         6         16           36   
1       36.829016         21          12        29          8           21   
2       36.304762         22           2         6         11            7   
3       36.822318         21          12        27         16           13   
4       36.833074         21          12        23         22            1   
...           ...        ...         ...       ...        ...          ...   
137853  36.690215         20           8        18         13           58   
137854  36.690215         20           8        23         19           19   
137855  36.690215         20           9         1         10           18   
137856  36.690215         20          10         4          0            0   
137857  36.690215         20          10        24         18           50   

        RECV_second                                   total_address  city  
0                37                인삼로, 아인리, 금산군, 충청남도, 32734, 대한민국    충남  
1                39      유성대로, 장대동, 온천2동, 온천동, 유성구, 대전, 34164, 대한민국    충남  
2                22              28, 석봉로, 석봉동, 대덕구, 대전, 34320, 대한민국    충남  
3                29    (주)계룡관광휴게소, 차령로, 기산리, 공주시, 충청남도, 32616, 대한민국    충남  
4                 6               대전로, 원동, 중앙동, 동구, 대전, 34626, 대한민국    충남  
...             ...                                             ...   ...  
137853           20  문화원로38번길, 장대동, 온천2동, 온천동, 유성구, 대전, 34168, 대한민국  충청남도  
137854           32                     대산리, 서산시, 충청남도, 31909, 대한민국  충청남도  
137855           15                금산로, 추정리, 금산군, 충청남도, 32712, 대한민국  충청남도  
137856           12                   중반8길, 변동, 서구, 대전, 35318, 대한민국  충청남도  
137857           12  아라리오갤러리, 만남로, 신부동, 동남구, 천안시, 충청남도, 31124, 대한민국  충청남도  

[137858 rows x 13 columns]

In [121]:
chungnam['weekday'] = chungnam['RECV_CPLT_DM'].apply(lambda x: x.weekday())
display(chungnam)

RECV_CPLT_DM  EVT_CL_CD         HPPN_PNU_ADDR      HPPN_X  \
0      2006-09-21 16:36:37        401           충남 논산시 가야곡면  127.174864   
1      2029-12-21 08:21:39        401  충남 천안시 동남구 신부동 16-11  127.169554   
2      2006-02-22 11:07:22        401    충남 보령시 남포면 옥서리 2-3  126.606069   
3      2027-12-21 16:13:29        401    충남 천안시 서북구 백석동 873  127.125026   
4      2023-12-21 22:01:06        401    충남 천안시 서북구 두정동 939  127.135951   
...                    ...        ...                   ...         ...   
137853 2018-08-20 13:58:20        401      충청남도 태안군 근흥면 도황리  126.191890   
137854 2023-08-20 19:19:32        401      충청남도 태안군 근흥면 도황리  126.191890   
137855 2001-09-20 10:18:15        401      충청남도 태안군 근흥면 도황리  126.191890   
137856 2004-10-20 00:00:12        401      충청남도 태안군 근흥면 도황리  126.191890   
137857 2024-10-20 18:50:12        401      충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  RECV_minute  \
0       36.158793         21           9         6         16           36   
1       36.829016         21          12        29          8           21   
2       36.304762         22           2         6         11            7   
3       36.822318         21          12        27         16           13   
4       36.833074         21          12        23         22            1   
...           ...        ...         ...       ...        ...          ...   
137853  36.690215         20           8        18         13           58   
137854  36.690215         20           8        23         19           19   
137855  36.690215         20           9         1         10           18   
137856  36.690215         20          10         4          0            0   
137857  36.690215         20          10        24         18           50   

        RECV_second                                   total_address  city  \
0                37                인삼로, 아인리, 금산군, 충청남도, 32734, 대한민국    충남   
1                39      유성대로, 장대동, 온천2동, 온천동, 유성구, 대전, 34164, 대한민국    충남   
2                22              28, 석봉로, 석봉동, 대덕구, 대전, 34320, 대한민국    충남   
3                29    (주)계룡관광휴게소, 차령로, 기산리, 공주시, 충청남도, 32616, 대한민국    충남   
4                 6               대전로, 원동, 중앙동, 동구, 대전, 34626, 대한민국    충남   
...             ...                                             ...   ...   
137853           20  문화원로38번길, 장대동, 온천2동, 온천동, 유성구, 대전, 34168, 대한민국  충청남도   
137854           32                     대산리, 서산시, 충청남도, 31909, 대한민국  충청남도   
137855           15                금산로, 추정리, 금산군, 충청남도, 32712, 대한민국  충청남도   
137856           12                   중반8길, 변동, 서구, 대전, 35318, 대한민국  충청남도   
137857           12  아라리오갤러리, 만남로, 신부동, 동남구, 천안시, 충청남도, 31124, 대한민국  충청남도   

        weekday  
0             3  
1             4  
2             2  
3             1  
4             3  
...         ...  
137853        0  
137854        6  
137855        3  
137856        2  
137857        6  

[137858 rows x 14 columns]

In [122]:
chungnam_mon = chungnam[chungnam['weekday'] == 0]
chungnam_tue = chungnam[chungnam['weekday'] == 1]
chungnam_wed = chungnam[chungnam['weekday'] == 2]
chungnam_thu = chungnam[chungnam['weekday'] == 3]
chungnam_fri = chungnam[chungnam['weekday'] == 4]
chungnam_sat = chungnam[chungnam['weekday'] == 5]
chungnam_sun = chungnam[chungnam['weekday'] == 6]

print(chungnam_mon.shape)
print(chungnam_tue.shape)
print(chungnam_wed.shape)
print(chungnam_thu.shape)
print(chungnam_fri.shape)
print(chungnam_sat.shape)
print(chungnam_sun.shape)

(19905, 14)
(19612, 14)
(19302, 14)
(19745, 14)
(19710, 14)
(19896, 14)
(19688, 14)


In [131]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_mon = hdbscan.HDBSCAN(min_cluster_size = 20, min_samples = 20, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_mon.fit(
    np.radians(
        [x for x in zip(chungnam_mon['HPPN_Y'],chungnam_mon['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=20, min_samples=20)

In [132]:
chungnam_mon['cluster'] = clusterer_mon.labels_

<ipython-input-132-0fee878cd66d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chungnam_mon['cluster'] = clusterer_mon.labels_


In [133]:
np.unique(clusterer_mon.labels_, return_counts = True)

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
         25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155], dtype=int64),
 array([7002,   51,  205,  121,   35,   34,   49,   53,  255,   39,  104,
          32,   72,   

In [134]:
chungnam_mon.to_csv('_4_HDBSCAN_요인별추출//chungnam_mon_minpt_20.csv')

### 세종 

In [11]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_sej = hdbscan.HDBSCAN(min_cluster_size =50, min_samples = 50, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_sej.fit(
    np.radians(
        [x for x in zip(sejong['HPPN_Y'],sejong['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=50, min_samples=50)

In [12]:
np.unique(clusterer_sej.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64),
 array([7011,  131,  142,   69,   61,  317,   70,  147,   82,   80,   91,
          72,   75,   61,  305,   54,   71,  180,   86,  255,   70,  127,
          83,  149,  315,   82,  291,  232,  129,   57,  101,  128,  252,
          89,  211,  136,  307,   65,  103,  233,   51,  117,   50,   67,
         438,  118,   59], dtype=int64))

In [48]:
sejong['cluster'] = clusterer_sej.labels_

In [49]:
sejong.to_csv('_4_HDBSCAN_요인별추출//sejong_eom_50.csv')

### 세종 - 연도별

In [106]:
sejong_20 = sejong[sejong['RECV_year'] == 20]
sejong_21 = sejong[sejong['RECV_year'] == 21]
sejong_22 = sejong[sejong['RECV_year'] == 22]
print(sejong_20.shape)
print(sejong_21.shape)
print(sejong_22.shape)

(4889, 8)
(3853, 8)
(4457, 8)


In [139]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_22 = hdbscan.HDBSCAN(min_cluster_size =20, min_samples = 20, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_22.fit(
    np.radians(
        [x for x in zip(sejong_22['HPPN_Y'],sejong_22['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=20, min_samples=20)

In [140]:
sejong_22['cluster'] = clusterer_22.labels_

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_24464\452045150.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sejong_22['cluster'] = clusterer_22.labels_


In [141]:
np.unique(clusterer_22.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       dtype=int64),
 array([1971,   22,   26,   48,   20,   91,   32,   24,   47,   59,   68,
          25,   25,   22,   26,   22,   66,   25,   42,   81,   39,   26,
          20,   63,  135,   91,  243,   53,   90,   32,   30,   31,   37,
          22,   27,   85,   24,   59,   44,   44,   54,   41,   47,   32,
         188,   23,   39,   29,   67], dtype=int64))

In [142]:
sejong_22.to_csv('_4_HDBSCAN_요인별추출//sejong_2022_minpt_20.csv')

### 세종 - 계절별

In [44]:
sejong_spring = sejong[np.logical_and(sejong['RECV_month'] >=3 ,sejong['RECV_month'] <= 5 ) ]
sejong_summer = sejong[np.logical_and(sejong['RECV_month'] >=6 ,sejong['RECV_month'] <= 8 ) ]
sejong_fall = sejong[np.logical_and(sejong['RECV_month'] >=9 ,sejong['RECV_month'] <= 11 ) ]
sejong_winter = sejong[np.logical_or(sejong['RECV_month'] ==12 ,sejong['RECV_month'] <= 2 ) ]

print(sejong_spring.shape)
print(sejong_summer.shape)
print(sejong_fall.shape)
print(sejong_winter.shape)

(3041, 8)
(3445, 8)
(3672, 8)
(3262, 8)


In [102]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_winter = hdbscan.HDBSCAN(min_cluster_size = 40, min_samples = 40, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_winter.fit(
    np.radians(
        [x for x in zip(sejong_winter['HPPN_Y'],sejong_winter['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=40, min_samples=40)

In [103]:
sejong_winter['cluster'] = clusterer_winter.labels_

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_24464\101923355.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sejong_winter['cluster'] = clusterer_winter.labels_


In [104]:
np.unique(clusterer_winter.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3,  4,  5], dtype=int64),
 array([ 412,  167,   64,   60, 1977,   70,  512], dtype=int64))

In [105]:
sejong_winter.to_csv('_4_HDBSCAN_요인별추출//sejong_winter_minpt_40.csv')

### 충남-요일별

In [31]:
sejong = sejong.reset_index()
sejong['RECV_CPLT_DM'] = pd.to_datetime(sejong['RECV_CPLT_DM'])
display(sejong)

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0     2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180   
1     2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611   
2     2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902   
3     2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694   
4     2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969   
...                   ...                             ...         ...   
13415 2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495   
13416 2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927   
13417 2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602   
13418 2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436   
13419 2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246   

          HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour     city  
0      36.601510         20          12         1         13  세종특별자치시  
1      36.603134         20          12         1         10  세종특별자치시  
2      36.522225         20          12         1         13  세종특별자치시  
3      36.717396         20          12         1         12  세종특별자치시  
4      36.504865         20          12         1         16  세종특별자치시  
...          ...        ...         ...       ...        ...      ...  
13415  36.503282         20          11        20         10  세종특별자치시  
13416  36.491494         20           2        24         13  세종특별자치시  
13417  36.514305         20           4         3         21  세종특별자치시  
13418  36.572830         20           9        15         16  세종특별자치시  
13419  36.526412         20          10        23          9  세종특별자치시  

[13420 rows x 9 columns]

In [32]:
sejong['weekday'] = sejong['RECV_CPLT_DM'].apply(lambda x: x.weekday())
display(sejong)

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0     2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180   
1     2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611   
2     2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902   
3     2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694   
4     2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969   
...                   ...                             ...         ...   
13415 2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495   
13416 2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927   
13417 2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602   
13418 2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436   
13419 2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246   

          HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour     city  weekday  
0      36.601510         20          12         1         13  세종특별자치시        1  
1      36.603134         20          12         1         10  세종특별자치시        1  
2      36.522225         20          12         1         13  세종특별자치시        1  
3      36.717396         20          12         1         12  세종특별자치시        1  
4      36.504865         20          12         1         16  세종특별자치시        1  
...          ...        ...         ...       ...        ...      ...      ...  
13415  36.503282         20          11        20         10  세종특별자치시        4  
13416  36.491494         20           2        24         13  세종특별자치시        0  
13417  36.514305         20           4         3         21  세종특별자치시        4  
13418  36.572830         20           9        15         16  세종특별자치시        1  
13419  36.526412         20          10        23          9  세종특별자치시        4  

[13420 rows x 10 columns]

In [33]:
sejong_mon = sejong[sejong['weekday'] == 0]
sejong_tue = sejong[sejong['weekday'] == 1]
sejong_wed = sejong[sejong['weekday'] == 2]
sejong_thu = sejong[sejong['weekday'] == 3]
sejong_fri = sejong[sejong['weekday'] == 4]
sejong_sat = sejong[sejong['weekday'] == 5]
sejong_sun = sejong[sejong['weekday'] == 6]

print(sejong_mon.shape)
print(sejong_tue.shape)
print(sejong_wed.shape)
print(sejong_thu.shape)
print(sejong_fri.shape)
print(sejong_sat.shape)
print(sejong_sun.shape)

(1961, 10)
(2084, 10)
(2042, 10)
(2081, 10)
(2211, 10)
(1768, 10)
(1273, 10)


In [114]:
kms_per_radian = 6371.0088
#epsilon /= kms_per_radian

clusterer_sun = hdbscan.HDBSCAN(min_cluster_size = 30, min_samples = 30, metric = 'haversine', cluster_selection_method = 'eom')
clusterer_sun.fit(
    np.radians(
        [x for x in zip(sejong_sun['HPPN_Y'],sejong_sun['HPPN_X'])]
    )
)

HDBSCAN(metric='haversine', min_cluster_size=30, min_samples=30)

In [115]:
sejong_sun['cluster'] = clusterer_sun.labels_

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_21176\2325177019.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sejong_sun['cluster'] = clusterer_sun.labels_


In [116]:
np.unique(clusterer_sun.labels_, return_counts = True)

(array([-1,  0,  1,  2,  3], dtype=int64),
 array([152,  47,  47, 289, 738], dtype=int64))

In [117]:
sejong_sun.to_csv('_4_HDBSCAN_요인별추출/sejong_sun_minpt_30.csv')

### 노이즈 제외 추출 

In [4]:
d_50 = pd.read_csv('_4_HDBSCAN_요인별추출//daejeon_eom_50.csv')
c_40 = pd.read_csv('_4_HDBSCAN_요인별추출//chungnam_eom_40.csv')
s_50 = pd.read_csv('_4_HDBSCAN_요인별추출//sejong_eom_50.csv')
display(d_50)
display(c_40)
display(s_50)

Unnamed: 0         RECV_CPLT_DM               HPPN_PNU_ADDR  \
0                0  2020-12-01 07:08:44     대전광역시 중구 석교동(석교동) 85-14   
1                1  2020-12-01 07:09:20  대전광역시 중구 석교동(행정:석교동) 88-11   
2                2  2020-12-01 01:39:03   대전광역시 동구 대동(행정:대동) 355-14   
3                3  2020-12-01 00:12:30    대전광역시 유성구 교촌동(진잠동) 411-1   
4                4  2020-12-01 00:09:52    대전광역시 유성구 교촌동(진잠동) 411-1   
...            ...                  ...                         ...   
104775      104775  2020-11-20 09:01:14                대전광역시 중구 중촌동   
104776      104776  2020-11-20 11:09:05                대전광역시 중구 중촌동   
104777      104777  2020-11-20 14:47:06                대전광역시 중구 중촌동   
104778      104778  2020-11-20 17:59:14                대전광역시 중구 중촌동   
104779      104779  2020-11-20 09:55:10                대전광역시 중구 중촌동   

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
2       127.447390  36.324597         20          12         1          1   
3       127.308197  36.308033         20          12         1          0   
4       127.308197  36.308033         20          12         1          0   
...            ...        ...        ...         ...       ...        ...   
104775  127.404663  36.341685         20          11        20          9   
104776  127.404663  36.341685         20          11        20         11   
104777  127.404663  36.341685         20          11        20         14   
104778  127.404663  36.341685         20          11        20         17   
104779  127.404663  36.341685         20          11        20          9   

        cluster  
0            87  
1            87  
2            -1  
3            -1  
4            -1  
...         ...  
104775       75  
104776       75  
104777       75  
104778       75  
104779       75  

[104780 rows x 10 columns]

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0       2020-12-01 08:17:50  충청남도 천안시 서북구 성정동(행정:성정2동) 1259  127.137160   
1       2020-12-01 01:36:38  충청남도 서산시 대산읍 대로리(행정:대산읍) 216-3  126.412290   
2       2020-12-01 02:23:03  충청남도 아산시 둔포면 송용리(행정:둔포면) 71-68  127.032318   
3       2020-12-01 02:24:26         충청남도 서산시 읍내동(부춘동) 733-2  126.438445   
4       2020-12-01 01:37:37     충청남도 서산시 대산읍 대로리(대산읍) 216-3  126.412245   
...                     ...                             ...         ...   
137853  2020-08-18 13:58:20                충청남도 태안군 근흥면 도황리  126.191890   
137854  2020-08-23 19:19:32                충청남도 태안군 근흥면 도황리  126.191890   
137855  2020-09-01 10:18:15                충청남도 태안군 근흥면 도황리  126.191890   
137856  2020-10-04 00:00:12                충청남도 태안군 근흥면 도황리  126.191890   
137857  2020-10-24 18:50:12                충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
0       36.826718         20          12         1          8      542  
1       36.967612         20          12         1          1      140  
2       36.921510         20          12         1          2       -1  
3       36.779188         20          12         1          2       -1  
4       36.967579         20          12         1          1      140  
...           ...        ...         ...       ...        ...      ...  
137853  36.690215         20           8        18         13      118  
137854  36.690215         20           8        23         19      118  
137855  36.690215         20           9         1         10      118  
137856  36.690215         20          10         4          0      118  
137857  36.690215         20          10        24         18      118  

[137858 rows x 9 columns]

RECV_CPLT_DM                   HPPN_PNU_ADDR      HPPN_X  \
0      2020-12-01 13:22:45             세종특별자치시 조치원읍 원리 13   127.303180   
1      2020-12-01 10:45:45  세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6  127.304611   
2      2020-12-01 13:07:38    세종특별자치시 세종시 부강면 부강리(행정:부강면)   127.368902   
3      2020-12-01 12:21:09    세종특별자치시 세종시 소정면 고등리(행정:소정면)   127.194694   
4      2020-12-01 16:51:57     세종특별자치시 세종시 종촌동(행정:종촌동) 677  127.246969   
...                    ...                             ...         ...   
13415  2020-11-20 10:12:32        세종특별자치시 세종시 어진동(행정:도담동)   127.267495   
13416  2020-02-24 13:18:01                 세종특별자치시 부강면 금호리  127.364927   
13417  2020-04-03 21:09:28                     세종특별자치시 도담동  127.258602   
13418  2020-09-15 16:24:11                 세종특별자치시 연서면 쌍전리  127.276436   
13419  2020-10-23 09:00:51                     세종특별자치시 해밀동  127.265246   

          HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  cluster  
0      36.601510         20          12         1         13       -1  
1      36.603134         20          12         1         10       21  
2      36.522225         20          12         1         13        4  
3      36.717396         20          12         1         12       -1  
4      36.504865         20          12         1         16       -1  
...          ...        ...         ...       ...        ...      ...  
13415  36.503282         20          11        20         10       -1  
13416  36.491494         20           2        24         13       -1  
13417  36.514305         20           4         3         21       35  
13418  36.572830         20           9        15         16       -1  
13419  36.526412         20          10        23          9       -1  

[13420 rows x 9 columns]

In [62]:
print(np.unique(d_50['cluster'],return_counts = True))
print(np.unique(c_40['cluster'],return_counts = True))
print(np.unique(s_50['cluster'],return_counts = True))

(array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [60]:
d_wn = d_50[d_50['cluster'] != -1]
c_wn = c_40[c_40['cluster'] != -1]
s_wn = s_50[s_50['cluster'] != -1]

display(d_wn)
display(c_wn)
display(s_wn)

RECV_CPLT_DM  EVT_CL_CD                         HPPN_PNU_ADDR  \
0       20/12/01 07:08:44        401               대전광역시 중구 석교동(석교동) 85-14   
1       20/12/01 07:09:20        401            대전광역시 중구 석교동(행정:석교동) 88-11   
5       20/12/01 00:22:16        401            대전광역시 서구 괴정동(행정:괴정동) 95-28   
8       20/12/01 15:03:46        401            대전광역시 유성구 복용동(행정:온천1동) 236   
11      20/12/01 12:38:01        401             대전광역시 동구 홍도동(행정:홍도동) 13-3   
...                   ...        ...                                   ...   
104769  20/04/29 11:03:03        401           대전 광역시 중구 대흥동(행정:대흥동) 524-1   
104771  20/06/06 21:30:20        401          대전 유성구 봉명동 동아벤처타워 1062  1062   
104776  20/09/11 19:08:40        401                 대전 서구 도안동 1502  1502    
104778  20/10/04 13:43:05        401                대전 서구 갈마1동 1268  1268    
104779  20/11/13 18:42:05        401  대전 서구 둔산1동 915 청사오피스텔,  915 청사오피스텔,    

            HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
0       127.447545  36.306724         20          12         1          7   
1       127.447175  36.306694         20          12         1          7   
5       127.382337  36.336437         20          12         1          0   
8       127.320380  36.338273         20          12         1         15   
11      127.429684  36.346885         20          12         1         12   
...            ...        ...        ...         ...       ...        ...   
104769  127.419400  36.323609         20           4        29         11   
104771  127.347850  36.348480         20           6         6         21   
104776  127.347620  36.320900         20           9        11         19   
104778  127.373930  36.346500         20          10         4         13   
104779  127.389100  36.359430         20          11        13         18   

        RECV_minute  RECV_second  \
0                 8           44   
1                 9           20   
5                22           16   
8                 3           46   
11               38            1   
...             ...          ...   
104769            3            3   
104771           30           20   
104776            8           40   
104778           43            5   
104779           42            5   

                                            total_address   city  cluster  
0                  대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시       87  
1                  대종로171번길, 호동, 석교동, 중구, 대전, 34690, 대한민국  대전광역시       87  
5                    괴정주유소, 가장로, 괴정동, 서구, 대전, 35297, 대한민국  대전광역시      249  
8              복용동로, 복용동, 온천1동, 온천동, 유성구, 대전, 34213, 대한민국  대전광역시       12  
11                       홍도로9번길, 홍도동, 동구, 대전, 34554, 대한민국  대전광역시      159  
...                                                   ...    ...      ...  
104769             고재6길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전      213  
104771  월봉4로, 쌍용동, 쌍용2동, 쌍용동, 서북구, 천안시, 충청남도, 31170, 대한민국     대전      111  
104776             102, 탕정면로, 명암리, 아산시, 충청남도, 31456, 대한민국     대전       54  
104778            고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전      286  
104779            고재12길, 구성동, 동남구, 천안시, 충청남도, 31187, 대한민국     대전      233  

[52349 rows x 14 columns]

RECV_CPLT_DM  EVT_CL_CD          HPPN_PNU_ADDR      HPPN_X  \
2       22/02/06 11:07:22        401     충남 보령시 남포면 옥서리 2-3  126.606069   
3       21/12/27 16:13:29        401     충남 천안시 서북구 백석동 873  127.125026   
5       21/12/24 22:26:22        401    충남 천안시 서북구 불당동 1540  127.107630   
8       21/12/23 17:03:01        401      충남 아산시 온천동 145-51  127.003786   
10      21/12/23 15:11:35        401  충남 서천군 장항읍 창선2리 611-3  126.695976   
...                   ...        ...                    ...         ...   
137853  20/08/18 13:58:20        401       충청남도 태안군 근흥면 도황리  126.191890   
137854  20/08/23 19:19:32        401       충청남도 태안군 근흥면 도황리  126.191890   
137855  20/09/01 10:18:15        401       충청남도 태안군 근흥면 도황리  126.191890   
137856  20/10/04 00:00:12        401       충청남도 태안군 근흥면 도황리  126.191890   
137857  20/10/24 18:50:12        401       충청남도 태안군 근흥면 도황리  126.191890   

           HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  RECV_minute  \
2       36.304762         22           2         6         11            7   
3       36.822318         21          12        27         16           13   
5       36.813805         21          12        24         22           26   
8       36.779972         21          12        23         17            3   
10      36.011343         21          12        23         15           11   
...           ...        ...         ...       ...        ...          ...   
137853  36.690215         20           8        18         13           58   
137854  36.690215         20           8        23         19           19   
137855  36.690215         20           9         1         10           18   
137856  36.690215         20          10         4          0            0   
137857  36.690215         20          10        24         18           50   

        RECV_second                                   total_address  city  \
2                22              28, 석봉로, 석봉동, 대덕구, 대전, 34320, 대한민국    충남   
3                29    (주)계룡관광휴게소, 차령로, 기산리, 공주시, 충청남도, 32616, 대한민국    충남   
5                22                            새롬동, 세종, 30126, 대한민국    충남   
8                 1  갈릴리교회, 다가11길, 다가동, 동남구, 천안시, 충청남도, 31154, 대한민국    충남   
10               35             비래동로32번길, 비래동, 대덕구, 대전, 34416, 대한민국    충남   
...             ...                                             ...   ...   
137853           20  문화원로38번길, 장대동, 온천2동, 온천동, 유성구, 대전, 34168, 대한민국  충청남도   
137854           32                     대산리, 서산시, 충청남도, 31909, 대한민국  충청남도   
137855           15                금산로, 추정리, 금산군, 충청남도, 32712, 대한민국  충청남도   
137856           12                   중반8길, 변동, 서구, 대전, 35318, 대한민국  충청남도   
137857           12  아라리오갤러리, 만남로, 신부동, 동남구, 천안시, 충청남도, 31124, 대한민국  충청남도   

        cluster  
2           153  
3           509  
5           515  
8           458  
10           77  
...         ...  
137853      117  
137854      117  
137855      117  
137856      117  
137857      117  

[75760 rows x 14 columns]

RECV_CPLT_DM  EVT_CL_CD                      HPPN_PNU_ADDR  \
1      20/12/01 10:45:45        401     세종특별자치시 세종시 조치원읍 상리(조치원읍) 39-6   
2      20/12/01 13:07:38        401       세종특별자치시 세종시 부강면 부강리(행정:부강면)    
7      20/12/01 21:00:31        401      세종특별자치시 세종시 보람동(행정:보람동) 622-1   
10     20/12/04 01:17:57        401           세종특별자치시 세종시 나성동(새롬동) 721   
11     20/12/04 01:16:44        401        세종특별자치시 세종시 나성동(행정:새롬동) 722   
...                  ...        ...                                ...   
13405  20/11/21 21:03:16        401  세종특별자치시 세종시 조치원읍 교리(행정:조치원읍) 10-4   
13410  20/11/20 11:53:56        401        세종특별자치시 세종시 한솔동(한솔동) 130-2    
13411  20/11/20 13:28:14        401        세종특별자치시 세종시 보람동(행정:보람동) 670   
13412  20/11/20 10:53:56        401    세종특별자치시 세종시 부강면 부강리(행정:부강면) 481   
13417  20/04/03 21:09:28        401                        세종특별자치시 도담동   

           HPPN_X     HPPN_Y  RECV_year  RECV_month  RECV_day  RECV_hour  \
1      127.304611  36.603134         20          12         1         10   
2      127.368902  36.522225         20          12         1         13   
7      127.293270  36.482200         20          12         1         21   
10     127.262514  36.480017         20          12         4          1   
11     127.262247  36.479612         20          12         4          1   
...           ...        ...        ...         ...       ...        ...   
13405  127.298023  36.604357         20          11        21         21   
13410  127.253278  36.473544         20          11        20         11   
13411  127.291009  36.477561         20          11        20         13   
13412  127.368017  36.528288         20          11        20         10   
13417  127.258602  36.514305         20           4         3         21   

       RECV_minute  RECV_second  \
1               45           45   
2                7           38   
7                0           31   
10              17           57   
11              16           44   
...            ...          ...   
13405            3           16   
13410           53           56   
13411           28           14   
13412           53           56   
13417            9           28   

                                         total_address     city  cluster  
1                          허만석로, 조치원읍, 세종, 30025, 대한민국  세종특별자치시       21  
2                          부강금호로, 부강면, 세종, 30086, 대한민국  세종특별자치시        4  
7          1003동, 210, 시청대로, 보람동, 호탄리, 세종, 30150, 대한민국  세종특별자치시       23  
10       세종메디피아, 165, 한누리대로, 나성동, 새롬동, 세종, 30130, 대한민국  세종특별자치시       44  
11     NK리움힐 상가, 161, 한누리대로, 나성동, 새롬동, 세종, 30130, 대한민국  세종특별자치시       44  
...                                                ...      ...      ...  
13405                      북계리, 공주시, 충청남도, 32513, 대한민국  세종특별자치시       24  
13410    206, 문화로, 문화동, 문화1동, 문화동, 중구, 대전, 34962, 대한민국  세종특별자치시       13  
13411      110, 신부8길, 신부동, 동남구, 천안시, 충청남도, 31125, 대한민국  세종특별자치시       23  
13412    새말사거리, 남부대로, 신방동, 동남구, 천안시, 충청남도, 31185, 대한민국  세종특별자치시        4  
13417     244, 불당25로, 불당동, 서북구, 천안시, 충청남도, 31094, 대한민국  세종특별자치시       35  

[6409 rows x 14 columns]

In [63]:
d_wn.to_csv('_4_HDBSCAN_요인별추출//daejeon_no noise.csv')
c_wn.to_csv('._4_HDBSCAN_요인별추출//chungnam_no noise.csv')
s_wn.to_csv('._4_HDBSCAN_요인별추출//sejong_no noise.csv')

In [4]:
daejeon_spring_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//daejeon_spring_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_summer_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//daejeon_summer_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_fall_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//daejeon_fall_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_winter_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//daejeon_winter_minpt_30.csv', encoding = 'utf-8', index_col = 0)
sejong_spring_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//sejong_spring_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_summer_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//sejong_summer_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_fall_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//sejong_fall_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_winter_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//sejong_winter_minpt_20.csv', encoding = 'utf-8', index_col = 0)
chungnam_spring_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//chungnam_spring_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_summer_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//chungnam_summer_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_fall_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//chungnam_fall_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_winter_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//계절별//chungnam_winter_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_2020_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//daejeon_2020_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_2021_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//daejeon_2021_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_2022_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//daejeon_2022_minpt_30.csv', encoding = 'utf-8', index_col = 0)
sejong_2020_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//sejong_2020_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_2021_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//sejong_2021_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_2022_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//sejong_2022_minpt_20.csv', encoding = 'utf-8', index_col = 0)
chungnam_2020_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//chungnam_2020_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_2021_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//chungnam_2021_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_2022_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//연도별//chungnam_2022_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_day_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//daejeon_day_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_night_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//daejeon_night_minpt_30.csv', encoding = 'utf-8', index_col = 0)
sejong_day_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//sejong_day_minpt_20.csv', encoding = 'utf-8', index_col = 0)
sejong_night_minpt_20 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//sejong_night_minpt_20.csv', encoding = 'utf-8', index_col = 0)
chungnam_day_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//chungnam_day_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_night_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//밤낮//chungnam_night_minpt_30.csv', encoding = 'utf-8', index_col = 0)

In [9]:
daejeon_spring_minpt_30 = daejeon_spring_minpt_30[daejeon_spring_minpt_30['cluster']!=-1]
daejeon_summer_minpt_30 = daejeon_summer_minpt_30[daejeon_summer_minpt_30['cluster']!=-1]
daejeon_fall_minpt_30 = daejeon_fall_minpt_30[daejeon_fall_minpt_30['cluster']!=-1]
daejeon_winter_minpt_30 = daejeon_winter_minpt_30[daejeon_winter_minpt_30['cluster']!=-1]
sejong_spring_minpt_20 = sejong_spring_minpt_20[sejong_spring_minpt_20['cluster']!=-1]
sejong_summer_minpt_20 = sejong_summer_minpt_20[sejong_summer_minpt_20['cluster']!=-1]
sejong_fall_minpt_20 = sejong_fall_minpt_20[sejong_fall_minpt_20['cluster']!=-1]
sejong_winter_minpt_20 = sejong_winter_minpt_20[sejong_winter_minpt_20['cluster']!=-1]
chungnam_spring_minpt_30 = chungnam_spring_minpt_30[chungnam_spring_minpt_30['cluster']!=-1]
chungnam_summer_minpt_30 = chungnam_summer_minpt_30[chungnam_summer_minpt_30['cluster']!=-1]
chungnam_fall_minpt_30 = chungnam_fall_minpt_30[chungnam_fall_minpt_30['cluster']!=-1]
chungnam_winter_minpt_30 = chungnam_winter_minpt_30[chungnam_winter_minpt_30['cluster']!=-1]
daejeon_2020_minpt_30 = daejeon_2020_minpt_30[daejeon_2020_minpt_30['cluster']!=-1]
daejeon_2021_minpt_30 = daejeon_2021_minpt_30[daejeon_2021_minpt_30['cluster']!=-1]
daejeon_2022_minpt_30 = daejeon_2022_minpt_30[daejeon_2022_minpt_30['cluster']!=-1]
sejong_2020_minpt_20 = sejong_2020_minpt_20[sejong_2020_minpt_20['cluster']!=-1]
sejong_2021_minpt_20 = sejong_2021_minpt_20[sejong_2021_minpt_20['cluster']!=-1]
sejong_2022_minpt_20 = sejong_2022_minpt_20[sejong_2022_minpt_20['cluster']!=-1]
chungnam_2020_minpt_30 = chungnam_2020_minpt_30[chungnam_2020_minpt_30['cluster']!=-1]
chungnam_2021_minpt_30 = chungnam_2021_minpt_30[chungnam_2021_minpt_30['cluster']!=-1]
chungnam_2022_minpt_30 = chungnam_2022_minpt_30[chungnam_2022_minpt_30['cluster']!=-1]
daejeon_day_minpt_30 = daejeon_day_minpt_30[daejeon_day_minpt_30['cluster']!=-1]
daejeon_night_minpt_30 = daejeon_night_minpt_30[daejeon_night_minpt_30['cluster']!=-1]
sejong_day_minpt_20 = sejong_day_minpt_20[sejong_day_minpt_20['cluster']!=-1]
sejong_night_minpt_20 = sejong_night_minpt_20[sejong_night_minpt_20['cluster']!=-1]
chungnam_day_minpt_30 = chungnam_day_minpt_30[chungnam_day_minpt_30['cluster']!=-1]
chungnam_night_minpt_30 = chungnam_night_minpt_30[chungnam_night_minpt_30['cluster']!=-1]

In [10]:
daejeon_spring_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_spring_minpt_30.csv')
daejeon_summer_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_summer_minpt_30.csv')
daejeon_fall_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_fall_minpt_30.csv')
daejeon_winter_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_winter_minpt_30.csv')
sejong_spring_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_spring_minpt_20.csv')
sejong_summer_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_summer_minpt_20.csv')
sejong_fall_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_fall_minpt_20.csv')
sejong_winter_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_winter_minpt_20.csv')
chungnam_spring_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_spring_minpt_30.csv')
chungnam_summer_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_summer_minpt_30.csv')
chungnam_fall_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_fall_minpt_30.csv')
chungnam_winter_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_winter_minpt_30.csv')
daejeon_2020_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_2020_minpt_30.csv')
daejeon_2021_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_2021_minpt_30.csv')
daejeon_2022_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_2022_minpt_30.csv')
sejong_2020_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_2020_minpt_20.csv')
sejong_2021_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_2021_minpt_20.csv')
sejong_2022_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_2022_minpt_20.csv')
chungnam_2020_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_2020_minpt_30.csv')
chungnam_2021_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_2021_minpt_30.csv')
chungnam_2022_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_2022_minpt_30.csv')
daejeon_day_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_day_minpt_30.csv')
daejeon_night_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_night_minpt_30.csv')
sejong_day_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_day_minpt_20.csv')
sejong_night_minpt_20.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_night_minpt_20.csv')
chungnam_day_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_day_minpt_30.csv')
chungnam_night_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_night_minpt_30.csv')

In [ ]:
daejeon_mon_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_mon_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_tue_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_tue_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_wed_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_wed_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_thu_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_thu_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_fri_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_fri_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_sat_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_sat_minpt_30.csv', encoding = 'utf-8', index_col = 0)
daejeon_sun_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//daejeon_sun_minpt_30.csv', encoding = 'utf-8', index_col = 0)
sejong_mon_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_mon_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_tue_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_tue_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_wed_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_wed_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_thu_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_thu_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_fri_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_fri_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_sat_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_sat_minpt_10.csv', encoding = 'utf-8', index_col = 0)
sejong_sun_minpt_10 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//sejong_sun_minpt_10.csv', encoding = 'utf-8', index_col = 0)
chungnam_mon_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_mon_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_tue_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_tue_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_wed_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_wed_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_thu_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_thu_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_fri_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_fri_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_sat_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_sat_minpt_30.csv', encoding = 'utf-8', index_col = 0)
chungnam_sun_minpt_30 = pd.read_csv('_4_HDBSCAN_요인별추출//군집데이터//요일별//chungnam_sun_minpt_30.csv', encoding = 'utf-8', index_col = 0)

In [12]:
daejeon_mon_minpt_30 = daejeon_mon_minpt_30[daejeon_mon_minpt_30['cluster']!=-1]
daejeon_tue_minpt_30 = daejeon_tue_minpt_30[daejeon_tue_minpt_30['cluster']!=-1]
daejeon_wed_minpt_30 = daejeon_wed_minpt_30[daejeon_wed_minpt_30['cluster']!=-1]
daejeon_thu_minpt_30 = daejeon_thu_minpt_30[daejeon_thu_minpt_30['cluster']!=-1]
daejeon_fri_minpt_30 = daejeon_fri_minpt_30[daejeon_fri_minpt_30['cluster']!=-1]
daejeon_sat_minpt_30 = daejeon_sat_minpt_30[daejeon_sat_minpt_30['cluster']!=-1]
daejeon_sun_minpt_30 = daejeon_sun_minpt_30[daejeon_sun_minpt_30['cluster']!=-1]
sejong_mon_minpt_10 = sejong_mon_minpt_10[sejong_mon_minpt_10['cluster']!=-1]
sejong_tue_minpt_10 = sejong_tue_minpt_10[sejong_tue_minpt_10['cluster']!=-1]
sejong_wed_minpt_10 = sejong_wed_minpt_10[sejong_wed_minpt_10['cluster']!=-1]
sejong_thu_minpt_10 = sejong_thu_minpt_10[sejong_thu_minpt_10['cluster']!=-1]
sejong_fri_minpt_10 = sejong_fri_minpt_10[sejong_fri_minpt_10['cluster']!=-1]
sejong_sat_minpt_10 = sejong_sat_minpt_10[sejong_sat_minpt_10['cluster']!=-1]
sejong_sun_minpt_10 = sejong_sun_minpt_10[sejong_sun_minpt_10['cluster']!=-1]
chungnam_mon_minpt_30 = chungnam_mon_minpt_30[chungnam_mon_minpt_30['cluster']!=-1]
chungnam_tue_minpt_30 = chungnam_tue_minpt_30[chungnam_tue_minpt_30['cluster']!=-1]
chungnam_wed_minpt_30 = chungnam_wed_minpt_30[chungnam_wed_minpt_30['cluster']!=-1]
chungnam_thu_minpt_30 = chungnam_thu_minpt_30[chungnam_thu_minpt_30['cluster']!=-1]
chungnam_fri_minpt_30 = chungnam_fri_minpt_30[chungnam_fri_minpt_30['cluster']!=-1]
chungnam_sat_minpt_30 = chungnam_sat_minpt_30[chungnam_sat_minpt_30['cluster']!=-1]
chungnam_sun_minpt_30 = chungnam_sun_minpt_30[chungnam_sun_minpt_30['cluster']!=-1]

In [13]:
daejeon_mon_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_mon_minpt_30.csv')
daejeon_tue_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_tue_minpt_30.csv')
daejeon_wed_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_wed_minpt_30.csv')
daejeon_thu_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_thu_minpt_30.csv')
daejeon_fri_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_fri_minpt_30.csv')
daejeon_sat_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_sat_minpt_30.csv')
daejeon_sun_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//daejeon_sun_minpt_30.csv')
sejong_mon_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_mon_minpt_10.csv')
sejong_tue_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_tue_minpt_10.csv')
sejong_wed_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_wed_minpt_10.csv')
sejong_thu_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_thu_minpt_10.csv')
sejong_fri_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_fri_minpt_10.csv')
sejong_sat_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_sat_minpt_10.csv')
sejong_sun_minpt_10.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//sejong_sun_minpt_10.csv')
chungnam_mon_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_mon_minpt_30.csv')
chungnam_tue_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_tue_minpt_30.csv')
chungnam_wed_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_wed_minpt_30.csv')
chungnam_thu_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_thu_minpt_30.csv')
chungnam_fri_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_fri_minpt_30.csv')
chungnam_sat_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_sat_minpt_30.csv')
chungnam_sun_minpt_30.to_csv('_4_HDBSCAN_요인별추출//군집데이터//no_noise//chungnam_sun_minpt_30.csv')